"""mudando nome da coluna products para product na tabela orders

Revision ID: dd661447dca3
Revises: 3b484dc206c7
Create Date: 2021-09-01 11:58:46.216115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd661447dca3'
down_revision = '3b484dc206c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
